### ISSUE TITLE
Data too long for column 'recommendedupdates'

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/softwareupdate#11]
`String data, right truncated: 1406 Data too long for column 'recommendedupdates' at row 1 (SQL: update `softwareupdate` set `lastattemptsystemversion` = 10.15.7 (19H15), `lastbackgroundsuccessfuldate` = 1662299616, `lastfullsuccessfuldate` = 1662299598, `lastrecommendedupdatesavailable` = 11, `lastsuccessfuldate` = 1662299598, `lastupdatesavailable` = 11, `recommendedupdates` = Safari, macOS Catalina 10.15.7 Supplemental Update, macOS Catalina Security Update 2021-002, macOS Catalina Security Update 2021-003, macOS Catalina Security Update 2021-004, macOS Catalina Security Update 2021-007, macOS Catalina Security Update 2021-008, macOS Catalina Security Update 2022-001, macOS Catalina Security Update 2022-003, macOS Catalina Security Update 2022-004, macOS Catalina Security Update 2022-005, `mrxprotect` = 1660234500, `xprotect_version` = 2162.0, `mrt_version` = 1.93, `mrt_last_modified` = 1650585756, `softwareupdate_history` = [{"date":"1418057169","display_name":"Digital Camera RAW Compatibility Update","display_version":"6.01","package_identifiers":["com.apple.pkg.RAWCameraUpdate6"]},{"date":"1418057169","display_name":"OS X Update","display_version":"10.10.1","package_identifiers":["com.apple.pkg.update.os.10.10.1.14B25.delta"]},{"date":"1418057169","display_name":"iTunes","display_version":"12.0.1","package_identifiers":["com.apple.pkg.iTunesX","com.apple.pkg.iTunesAccess","com.apple.pkg.CoreFP","com.apple.pkg.CoreADI","com.apple.pkg.MobileDevice"]},{"date":"1421084209","display_name":"Command Line Tools (OS X 10.10)","display_version":"6.0","package_identifiers":`...

This error message is very long. I tried increasing the varchar limit to 500 but that didn't help. I'm not sure if the client has an issue.

**Comment by tuxudo** [comment]
Client is having problems detecting what updates it has to install, there are multiple Catalina Security Updates pending to be installed. Once one of them is installed, the problem will be resolved.
