### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by illudium** [munkireport/softwareupdate#4]
Requesting to see a default page/Dashboard widget for softwareupdate, to show (say, for example), the two or three latest "recommended updates" in softwareupdate for clients,
in similar fashion to the Pending Apple Updates feature.

It seems that when Munki clients are set to `InstallAppleSoftwareUpdates` FALSE,
that the Pending Apple Update area is then empty.

Thank-you !!

**Comment by tuxudo** [comment]
New widget added with latest pull request that provides pending and ignored Apple updates widget

**Comment by illudium** [comment]
Wonderful, thanks ! What's the name of the widget ? :)
I see pending_apple but that's already active and perhaps not what you mean(t)

**Comment by tuxudo** [comment]
The two new widgets are `softwareupdate_pending_recommended_updates` and `softwareupdate_ignored_updates`
