### ISSUE TITLE
No data displayed under 'Software Updates' device record section

### ISSUE THREAD

**Issue by apizz** [munkireport/softwareupdate#6]
I recently spun up a Docker instance of munkireport for testing and enrolled a device on my network with it.  While the overwhelming majority of modules I've enabled are working as expected, I'm seeing some weirdness that I'm not sure if point to an issue in my setup or with this module.

To be clear, it's correctly loading data:

<img width="1781" alt="Screen Shot 2021-02-26 at 1 21 26 PM" src="https://user-images.githubusercontent.com/11789931/109339653-ee354380-7835-11eb-9e42-0eb196fce6bf.png">
<img width="1781" alt="Screen Shot 2021-02-26 at 1 21 32 PM" src="https://user-images.githubusercontent.com/11789931/109339654-eecdda00-7835-11eb-8cd8-510f213fa5a3.png">

But under the device record under software updates, nothing appears ...

<img width="1792" alt="Screen Shot 2021-02-26 at 10 11 37 AM" src="https://user-images.githubusercontent.com/11789931/109339769-1fae0f00-7836-11eb-97dd-2d8e825a42e4.png">

**Comment by tuxudo** [comment]
Resolved with PR #7 and version 1.7. Thank you for the bug report :)

**Comment by apizz** [comment]
Thanks for resolving this so quickly!  I've updated all the modules in my Docker container via `composer update --no-dev` and confirm that v1.7 is installed and that the data displays correctly!
🍻
